{% set name = "cz-changeup" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cz_changeup-{{ version }}.tar.gz
  sha256: c95565fbdc5bf288224f4ad57733f54e18156d18da943730c41ce961faa1d77d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - commitizen >=3.0.0,<4.0.0

test:
  imports:
    - cz_changeup
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/kmnhan/cz-changeup
  summary: Commitizen plugin for better changelog generation
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/kmnhan/cz-changeup

extra:
  recipe-maintainers:
    - kmnhan
